### ISSUE TITLE
Grid layout for the gallery page instead of one column

### ISSUE THREAD

**Issue by jbampton** [fuchsia-programming/fuchsia-programming.github.io#112]
Display all of our logos in a rectangular responsive grid.

**Comment by vicainelli** [comment]
What about this?

![image](https://user-images.githubusercontent.com/1155694/66599793-7439e700-eb7a-11e9-8add-9e29196c83d8.png)

**Comment by jbampton** [comment]
Hey @vicainelli that looks great 👍
