### ISSUE TITLE
Add 512px by 512px Fuchsia logo to the web app manifest

### ISSUE THREAD

**Issue by jbampton** [fuchsia-programming/fuchsia-programming.github.io#141]
https://developers.google.com/web/tools/lighthouse/audits/custom-splash-screen

Logo to go here -> https://github.com/fuchsia-programming/fuchsia-programming.github.io/tree/master/assets/images/icons
 
and the `manifest.json` is in that directory too.

From the current Google Lighthouse report:

![Screen Shot 2019-11-23 at 8 14 48 pm](https://user-images.githubusercontent.com/418747/69477116-f5e58b80-0e2d-11ea-8ca2-43fac8b8a2be.png)

https://developers.google.com/web/tools/lighthouse

**Comment by jbampton** [comment]
Hey @grfxwzdesigner can you please add the 512px logo here in this issue as an attachment 👍

**Comment by grfxwzdesigner** [comment]
What 512px logo are you referring to?

**Comment by grfxwzdesigner** [comment]
Here it is.
![Fuchsia 512x512](https://user-images.githubusercontent.com/33774837/69474501-418d2c00-0d7f-11ea-86e5-e8fc382252c3.png)
