### ISSUE TITLE
Animated heading does not show up in Edge browser

### ISSUE THREAD

**Issue by grfxwzdesigner** [fuchsia-programming/fuchsia-programming.github.io#143]
The animated heading on this page does not show up in the Edge browser:
https://fuchsia-programming.github.io/
The heading should alternate Pink, Purple, Fuchsia
It shows in Firefox 64 bit, Ice Dragon and Chrome, but not in Edge.  See the screenshot of the functional heading.
![Animated Heading](https://user-images.githubusercontent.com/33774837/69475321-d47e9400-0d88-11ea-8856-bf39def79c92.JPG)

**Comment by jbampton** [comment]
fixed by #169
